# Generated by Django 5.2.13 on 2026-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('poster', models.URLField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('rated', models.CharField(blank=True, max_length=20, null=True)),
                ('released', models.CharField(blank=True, max_length=50, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('metascore', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('movie_type', models.CharField(blank=True, max_length=20, null=True)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('watched', 'تماشا شده'), ('want-to-watch', 'میخواهم ببینم')], default='want-to-watch', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
