name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ 178.173.144.194 }}
          username: ${{ erfan }}
          key: ${{ -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBp8Hf/b1iepaUyxsCtdDK9IKd+BKIj6IT6nblC9KJ37wAAAJAIomvCCKJr
wgAAAAtzc2gtZWQyNTUxOQAAACBp8Hf/b1iepaUyxsCtdDK9IKd+BKIj6IT6nblC9KJ37w
AAAECaktSYi38U7lGY9wnJr6RmQeDhpFceHAITzOushTrDcWnwd/9vWJ6lpTLGwK10Mr0g
p34EoiPohPqduUL0onfvAAAADGVyZmFuQFdheWxvbgE=
-----END OPENSSH PRIVATE KEY----- }}
          source: "frontend/dist/"
          target: "/home/erfan/frontend/"